# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: db
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - net
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
      - ./volumes/db_logs:/var/lib/postgresql/logs
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: home-library-service
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      - net

networks:
  net:
    driver: bridge
